### ISSUE TITLE
Default Bond thickness

### ISSUE THREAD

**Issue by Kohulan** [BTheDragonMaster/pikachu#1]
Hey,

Really nice python package. Excited to see further developments.
I tried the draw functionality of the package and found the default Bond thickness to be higher than most of the other toolkits. Probably setting a lower thickness would benefit most of the users.
SMILES: CN1C=NC2=C1C(=O)N(C(=O)N2C)C

**pikachu**
![image](https://user-images.githubusercontent.com/30716951/172581063-0370e6e1-3d2a-4618-b10c-814e31c18f1e.png)

**CDK-Depict**
![image](https://user-images.githubusercontent.com/30716951/172581147-8d45c44a-6b8a-461a-8900-0e5d78d61548.png)

Do let me know once you have updated the documentation.

Kind regards,
Kohulan

**Comment by BTheDragonMaster** [comment]
Thank you for your suggestion! I have added the option to manually set bond thickness as desired: [see PIKAChU wiki](https://github.com/BTheDragonMaster/pikachu/wiki/Customising-drawings)
<img width="188" alt="default_bonds" src="https://user-images.githubusercontent.com/47810869/172596327-4da402fc-f105-4731-9380-96406caa3dda.png"> <img width="184" alt="thin_bonds" src="https://user-images.githubusercontent.com/47810869/172596278-6ee7452c-3025-4af4-bb8f-9475057bb6c6.png">
