### ISSUE TITLE
Save structure to file

### ISSUE THREAD

**Issue by YingjieShao** [BTheDragonMaster/pikachu#2]
Hello!

I met a problem while trying to save the structure with  `smile.general.smiles_to_molfile()`. I would be grateful if you could help.

To check if there is an issue with the molecular, I also try to draw it with the NCBI online tool(https://pubchem.ncbi.nlm.nih.gov//edit3/index.html). The SMILE string, structure and error message are following. 

`CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C=O)C(C)(C)CCC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1.O`

![error message](https://user-images.githubusercontent.com/106308623/173882745-d5b07c8b-61ee-4338-8fc1-9834e11010ac.png)
![structure](https://user-images.githubusercontent.com/106308623/173885340-a9e48e51-1113-4a3e-936a-a52d167361ea.png)
 
Thank you!

**Comment by BTheDragonMaster** [comment]
Dear Lokious,

Thank you for pointing us to this issue! There was a problem with writing multiple structures to the same canvas, which we now fixed:

```
smiles_to_molfile(r"CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C=O)C(C)(C)CCC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1.O",` "test.mol")
```

<img width="547" alt="Screenshot 2022-06-16 at 11 46 29" src="https://user-images.githubusercontent.com/47810869/174044186-1e259746-bde2-4e61-a3d4-878ff2e5b632.png">

**Comment by YingjieShao** [comment]
Thank you!
